import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "./Header";
import { Separator } from "@/components/ui/separator";
import Provider from "./provider/Provider";
import { Toaster } from "sonner";
import dotenv from "dotenv";
dotenv.config();
import "./globals.css";
import MusicPlayer from "../components/MusicPlayer";
import AuthLoader from "./provider/AuthLoader";
import MainContent from "./MainContent";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Music App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen`}
      >
        <Provider>
          <Toaster />
          <AuthLoader />
          <Header />
          <MainContent>{children}</MainContent>
          <MusicPlayer />
        </Provider>
      </body>
    </html>
  );
}
