import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "./Header";
import { Separator } from "@/components/ui/separator";
import Provider from "./provider/Provider";
import { Toaster } from "sonner";
import dotenv from "dotenv";
dotenv.config();
import "./globals.css";
import MusicPlayer from "../components/MusicPlayer";
import { MusicProvider } from "./provider/MusicContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen `}
        >
          <Toaster />
          <Header />
          <MusicProvider>
            <main className="flex-1">{children}</main>
            <Separator className="mt-20" />
            <MusicPlayer />
          </MusicProvider>
        </body>
      </html>
    </Provider>
  );
}
