export const SOUNDCLOUD_GENRES = [
  { name: "All Music", id: "all-music" },
  { name: "Alternative Rock", id: "alternative-rock" },
  { name: "Ambient", id: "ambient" },
  { name: "Classical", id: "classical" },
  { name: "Country", id: "country" },
  { name: "Dance & EDM", id: "danceedm" },
  { name: "Dancehall", id: "dancehall" },
  { name: "Deep House", id: "deep-house" },
  { name: "Disco", id: "disco" },
  { name: "Drum & Bass", id: "dnb" },
  { name: "Dubstep", id: "dubstep" },
  { name: "Electronic", id: "electronic" },
  { name: "Folk", id: "folk" },
  { name: "Hip-hop & Rap", id: "hiphoprap" },
  { name: "House", id: "house" },
  { name: "Indie", id: "indie" },
  { name: "Jazz & Blues", id: "jazzblues" },
  { name: "Latin", id: "latin" },
  { name: "Metal", id: "metal" },
  { name: "Piano", id: "piano" },
  { name: "Pop", id: "pop" },
  { name: "R&B & Soul", id: "rbsoul" },
  { name: "Reggae", id: "reggae" },
  { name: "Reggaeton", id: "reggaeton" },
  { name: "Rock", id: "rock" },
  { name: "Soundtrack", id: "soundtrack" },
  { name: "Tech House", id: "techhouse" },
  { name: "Techno", id: "techno" },
  { name: "Trance", id: "trance" },
  { name: "Trap", id: "trap" },
  { name: "Trip Hop", id: "triphop" },
  { name: "World", id: "world" },
];
